# This is a basic workflow to help you get started with Actions

name: Deploy app to Hicoria

# Controls when the action will run. 

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /root/wifi-api
            git checkout -- .
            git pull
            npm install
            echo "DONE"
            cd /root/wifi-api/src
            pm2 restart main_app --update-env
            pm2 restart com_app --update-env
