name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          echo Branch ${{ github.event.pull_request.head.ref }}
          echo PR ${{ github.event.pull_request.number }}
